{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.opencode-harness;
  # Reuse built-in IDs to retain OpenCode's root detection; JSON is custom.
  servers = {
    nix = {
      package = pkgs.nixd;
      id = "nixd";
      command = [ "${pkgs.nixd}/bin/nixd" ];
    };
    typescript = {
      package = pkgs.typescript-language-server;
      id = "typescript";
      command = [
        "${pkgs.typescript-language-server}/bin/typescript-language-server"
        "--stdio"
      ];
    };
    python = {
      package = pkgs.pyright;
      id = "pyright";
      command = [
        "${pkgs.pyright}/bin/pyright-langserver"
        "--stdio"
      ];
    };
    bash = {
      package = pkgs.bash-language-server;
      id = "bash";
      command = [
        "${pkgs.bash-language-server}/bin/bash-language-server"
        "start"
      ];
    };
    yaml = {
      package = pkgs.yaml-language-server;
      id = "yaml-ls";
      command = [
        "${pkgs.yaml-language-server}/bin/yaml-language-server"
        "--stdio"
      ];
    };
    json = {
      package = pkgs.vscode-langservers-extracted;
      id = "json-ls";
      command = [
        "${pkgs.vscode-langservers-extracted}/bin/vscode-json-language-server"
        "--stdio"
      ];
      extensions = [
        ".json"
        ".jsonc"
      ];
    };
    go = {
      package = pkgs.gopls;
      id = "gopls";
      command = [ "${pkgs.gopls}/bin/gopls" ];
    };
  };
  enabledServers = lib.filterAttrs (name: _: cfg.lsp.${name}.enable) servers;
in
{
  options.programs.opencode-harness = {
    lsp = lib.mapAttrs (name: _: {
      enable = lib.mkEnableOption "the ${name} language server";
    }) servers;

    generatedLspSettings = lib.mkOption {
      type = lib.types.attrs;
      internal = true;
      readOnly = true;
      description = "OpenCode LSP settings generated by enabled harness language servers.";
    };
  };

  config = {
    home.packages = lib.mkIf cfg.enable (
      lib.unique (lib.mapAttrsToList (_: server: server.package) enabledServers)
    );
    programs.opencode-harness.generatedLspSettings = lib.optionalAttrs cfg.enable (
      lib.mapAttrs' (
        _: server:
        lib.nameValuePair server.id (
          builtins.removeAttrs server [
            "package"
            "id"
          ]
        )
      ) enabledServers
    );
  };
}
